#!/bin/bash

function handle_sigint()
{
    for proc in `jobs -p`
    do
        kill $proc
    done
}

trap handle_sigint SIGINT

usage() {
    echo $@
    echo "Usage $0 <url> [prove options]"
    echo "Examples :"
    echo "    $0 http://data-stage.globalchange.gov"
    echo "    $0 http://data-stage.globalchange.gov -v"
    exit 1;
}

# url
url=$1
[ -z "$url" ] && usage "missing url" ;
echo "# testing content of $url"
export GCIS_API_URL=$url

# args
args=$2

# do it
prove $args t/*.t

